### ISSUE TITLE
Noob Question: How to use?

### ISSUE THREAD

**Issue by elisaado** [Frederikam/JCA#1]
I've got it installed and imported but I really don't know what to do now!

Help is appreciated :heart: 

(Sorry for opening the first issue btw)

,
Eli

**Comment by freyacodes** [comment]
Hey there,

I built this as my first lib thinking no-one would use it, 10 months ago. Hence the lack of docs.

Usage is quite simple. Construct an instance of `JCABuilder` and add your credentials from https://cleverbot.io/

Then build the JCA instance and invoke `JCA#getResponse()`

**Comment by elisaado** [comment]
Woah is it that simple?

Thanks! :smile: 

,
Eli
